### PR TITLE
Fix hebrew translation in settings

### PR DESCRIPTION
**Pull request by BLooperZ**
Hi,
Thank you for the great work migrating Hebrew translation into the game.
I would like to suggest some fixes for the Hebrew translation.

Thanks

BTW,
"Virus" in hebrew is "נגיף",
but if it was translated this way ("וירוס") in the original 1998 translation, we should consider keeping it.

Edit:
PS,
Is there any chance the original translation will eventually become available at blupi.org?

### CODE REVIEW

**Comment by Skywalker13** [comment]
Yes, I've just asked to https://twitter.com/TShwarma it's opinion since he did the previous review.

**Comment by BLooperZ** [comment]
Thanks.

I mean the legacy archives section (where there are ISOs of the old commercial releases)... 
Just a naive question... if it will not be available there it's completely understandable, of course.

**Comment by Skywalker13** [comment]
Sorry I can't; and for Planet Blupi (like for CoLoBoT) I prefer that people use the new versions. A lot of bugs are fixed, there are more translations and a very good support for all OS (Windows, macOS and Linux). The original versions have too much bugs, use a lot of CPU and depends only of a very old version of DirectX.

**Comment by Skywalker13** [comment]
Thank you

**Pull request merged**
