### PR TITLE
improved Little.png font

### PR DESCRIPTION
**Pull request by jummy0**

### CODE REVIEW

**Comment by Skywalker13** [comment]
Hi, thanks for this merge request. Can you provide some screenshots please? (in different languages)

I can't test just know, but if it looks fine according to the screenshots, I merge.

**Comment by jummy0** [comment]
|language|before|after|
|-----|-----|-----|
|English|image|image
|German|image|image
|Polish|image|image
|Turkish|image|image
|Hebrew|image|image
|cheats display (top-left corner)|image|image

**Comment by jummy0** [comment]
This will have a greater effect for Speedy Blupi, where the Little font is not always on a dark background  (without editing `table_width_little` I can't fix the letters T and R)
image
image

**Comment by Skywalker13** [comment]
Good work, thank you

**Pull request merged**
