### PR TITLE
The planetblupi executable goes to /usr/games, not /usr/bin

### PR DESCRIPTION
**Pull request by OdyX**

### CODE REVIEW

**Comment by Skywalker13** [comment]
Seriously; it's in posix? Or it's just debian which is doing that?

If I apply this MR just like this, (I think) it breaks my AppImage, the macOS .app and the Windows installer.

But I'm ok for this change because it doesn't matter for my static builds...

**Comment by OdyX** [comment]
This is in FHS 3.0. http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s03.html

You don't need to integrate that, I can patch it in Debian :-)

**Comment by Skywalker13** [comment]
Finally I prefer to keep the executable in `/usr/bin` here.

**Comment by OdyX** [comment]
No problem. I've found another way to satisfy us both: use `GNUInstallDirs` https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html , so that I can just append a `-DCMAKE_INSTALL_BINDIR=games` in the configuration call.

I've pushed that fix here.

**Pull request merged**
